<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>Azure Service Bus trigger for WorkR.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkR\WorkR.csproj" />
  </ItemGroup>

</Project>
