<Project>

  <PropertyGroup>
    <Authors>James Law</Authors>
    <Copyright>Copyright © James Law</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/alterius/WorkR</PackageProjectUrl>
    <RepositoryUrl>https://github.com/alterius/WorkR</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>worker;background-worker;hosted-service;dotnet;</PackageTags>
    <PackageIcon>logo_128.png</PackageIcon>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\assets\logo\logo_128.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300" PrivateAssets="all" />
  </ItemGroup>

</Project>
